### ISSUE TITLE
Installation with pip fails for python 2.7.16

### ISSUE THREAD

**Issue by sergiohcdna** [threeML/threeML#355]
I tried to install threeML using python 2.7.16, but after getting some required packages, pip fail the installation because there is not any available version of zeus-mcmc for python 2.7

The output of this error is:

Collecting astroquery
  Using cached astroquery-0.4.tar.gz (4.5 MB)
Requirement already satisfied: corner in /home/shkdna/.local/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (2.0.1)
Collecting pandas
  Using cached pandas-0.24.2-cp27-cp27mu-manylinux1_x86_64.whl (10.1 MB)
Requirement already satisfied: requests in /home/shkdna/.local/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (2.18.4)
Requirement already satisfied: speclite in /home/shkdna/.local/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (0.5)
Requirement already satisfied: ipython in ./externals/16042020/External/python/2.7.17/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (5.9.0)
Requirement already satisfied: ipyparallel in /home/shkdna/.local/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (6.0.2)
Requirement already satisfied: numexpr in /home/shkdna/.local/lib/python2.7/site-packages (from threeML==1.0.4+3.g25fa51d) (2.6.2)
Collecting chainconsumer
  Using cached ChainConsumer-0.31.0.tar.gz (42 kB)
Collecting ultranest
  Using cached ultranest-2.1.2.tar.gz (20.7 MB)
ERROR: Could not find a version that satisfies the requirement zeus-mcmc (from threeML==1.0.4+3.g25fa51d) (from versions: none)
ERROR: No matching distribution found for zeus-mcmc (from threeML==1.0.4+3.g25fa51d)

**Comment by grburgess** [comment]
Thanks for finding this. Yes, we have recently migrated to python3 and this was a mistake to include zeus by default as it is only python3. I will push a fix in a few moments.

**Comment by grburgess** [comment]
@sergiohcdna, @ndilalla will push the new master to pip later today. However, you can install manually from the master now and it should work. Sorry for the error

**Comment by sergiohcdna** [comment]
Thanks, I will try now the installing this version

**Comment by sergiohcdna** [comment]
I tried the installation from the master. The installation goes fine. But when I trying a simple import I got the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/threeML/__init__.py", line 257, in <module>
    from threeML.catalogs import *
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/root/5.34.38/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/threeML/catalogs/__init__.py", line 1, in <module>
    from .Fermi import FermiGBMBurstCatalog, FermiLATSourceCatalog, FermiLLEBurstCatalog
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/root/5.34.38/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/threeML/catalogs/Fermi.py", line 7, in <module>
    from .VirtualObservatoryCatalog import VirtualObservatoryCatalog
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/root/5.34.38/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/threeML/catalogs/VirtualObservatoryCatalog.py", line 6, in <module>
    from astroquery.vo_conesearch.vos_catalog import VOSCatalog
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/root/5.34.38/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/astroquery/vo_conesearch/__init__.py", line 32, in <module>
    from .core import ConeSearch  # noqa
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/root/5.34.38/lib/root/ROOT.py", line 352, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/home/shkdna/hawcSoft16042020/externals/16042020/External/python/2.7.17/lib/python2.7/site-packages/astroquery/vo_conesearch/core.py", line 62
    def query_region(self, coordinates, radius, *, verb=1,
                                                 ^
SyntaxError: invalid syntax


I am not sure if this is a threeML related, or I need to check this issue with astroquery

**Comment by grburgess** [comment]
Indeed. This is man issue with the version of astro. You will need to make sure you have a clean environment and install.

**Comment by sergiohcdna** [comment]
Ok.

I will try this later. Thanks for your help :)

**Comment by sergiohcdna** [comment]
Hi!

I successfully installed threeML (from master). To solve the problem with astroquery I noted that threeML install astroquery 0.4 by default but installing astroquery 0.3.10, solve the problem.

Thanks for your help :)

**Comment by grburgess** [comment]
Ah, yes, this seems like a python2 thing. Are you tied to python2?

**Comment by sergiohcdna** [comment]
Yes.
For several reasons, the analysis software I am using is only available in python 2

**Comment by grburgess** [comment]
Ah ok. Glad we could fix that. Closing!
