### ISSUE TITLE
Root minimizer broken?

### ISSUE THREAD

**Issue by cbrisboi** [threeML/threeML#387]
I was running a test fit with hawc_hal last night and today. Today I spent some time creating a minimal example.

Using the HAWC public data set and a stripped down version of the basic example from the readme of hawc_hal, I have found that although the root minimizer is giving difficulties, minuit does not appear to have the same issue. It may be that a simple fix is available. I mentioned this on a HAWC call earlier today and an undergrad pointed out to me privately that allegedly newer versions of pyROOT  use `ROOT.double()` rather than `ROOT.Double()`, so this may be the issue (though there may be others). I created my environment yesterday using 

```
conda create --name new_hal -c conda-forge -c threeml numpy scipy matplotlib ipython numba reproject "astromodels>=2" "threeml>=2" root
conda activate new_hal
pip install --no-binary :all: root_numpy
pip install git+https://github.com/threeml/hawc_hal.git
```
I then used this environment on a CentOS 7 machine. 

Here is the example script
```
from hawc_hal import HAL, HealpixConeROI
import matplotlib.pyplot as plt
from threeML import *

# Define the ROI
ra_crab, dec_crab = 83.63, 22.02
data_radius = 3.0
model_radius = 8.0

roi = HealpixConeROI(data_radius=data_radius,
                     model_radius=model_radius,
                     ra=ra_crab,
                     dec=dec_crab)

# Instance the plugin
maptree = "HAWC_9bin_507days_crab_data.hd5"   # This can be either a ROOT or a hdf5 file
response = "HAWC_9bin_507days_crab_response.hd5" # This can be either a ROOT or hdf5 file

hawc = HAL("HAWC",
           maptree,
           response,
           roi)

# Use from bin 1 to bin 9
hawc.set_active_measurements(1, 9)

# Define model as usual
spectrum = Log_parabola()
source = PointSource("crab", ra=ra_crab, dec=dec_crab, spectral_shape=spectrum)

spectrum.piv = 7 * u.TeV
spectrum.piv.fix = True

spectrum.K = 1e-14 / (u.TeV * u.cm ** 2 * u.s)  # norm (in 1/(keV cm2 s))
spectrum.K.bounds = (1e-25, 1e-19)  # without units energies are in keV

spectrum.beta = 0  # log parabolic beta
spectrum.beta.bounds = (-4., 2.)

spectrum.alpha = -2.5  # log parabolic alpha (index)
spectrum.alpha.bounds = (-4., 2.)

model = Model(source)

data = DataList(hawc)

print("Perform fit using minuit")
jl = JointLikelihood(model, data, verbose=False)
jl.set_minimizer("minuit")
jl.fit()
jl.get_errors()

print("")
print("")

print("Now using Root")
jl2 = JointLikelihood(model, data, verbose=False)
jl2.set_minimizer("root")
jl2.fit()
print("And now everything goes wrong...")
jl2.get_errors()
```

The python traceback before the core dump is 
```Traceback (most recent call last):
  File "root_example.py", line 62, in <module>
    jl2.get_errors()
  File "/data/disk01/home/cbrisboi/hawc_software/miniconda3/envs/new_hal/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py", line 385, in get_errors
    errors = self._minimizer.get_errors()
  File "/data/disk01/home/cbrisboi/hawc_software/miniconda3/envs/new_hal/lib/python3.7/site-packages/threeML/minimizer/minimization.py", line 1082, in get_errors
    errors_dict = self._get_errors()
  File "/data/disk01/home/cbrisboi/hawc_software/miniconda3/envs/new_hal/lib/python3.7/site-packages/threeML/minimizer/ROOT_minimizer.py", line 212, in _get_errors
    err_low = ROOT.Double(0)
  File "/data/disk01/home/cbrisboi/hawc_software/miniconda3/envs/new_hal/lib/python3.7/site-packages/ROOT/_facade.py", line 163, in _fallback_getattr
    raise AttributeError("Failed to get attribute {} from ROOT".format(name))
AttributeError: Failed to get attribute Double from ROOT
```

The output of the script is contained in this logfile:
[minimal.log](https://github.com/threeML/threeML/files/5556566/minimal.log)

This has a relatively simple workaround, by simply using minuit rather than root, but still should be addressed somehow.

**Comment by henrikef** [comment]
Hi Chad! I can reproduce this error.

Note that the example is not executable as is, but the missing files can actually be downloaded from

https://data.hawc-observatory.org/datasets/crab_data/public_data/crab_2017/HAWC_9bin_507days_crab_response.hd5 and
https://data.hawc-observatory.org/datasets/crab_data/public_data/crab_2017/HAWC_9bin_507days_crab_data.hd5
