### ISSUE TITLE
test_parallel_pagmo fails

### ISSUE THREAD

**Issue by ndilalla** [threeML/threeML#419]
I don't know the reason but right now the test `test_parallel_pagmo` is failing even without `root` installed (see the log below). 

A bit of history and context: in the past we discovered that for an unkown reason this test was incompatible with `root`. So we decided to skip it if `root` was installed on the system---and this is the reason why this test is not failing on the standard CI actions. But since we have set up new a cron job testing the full installation process with conda, it started to crash without `root`. See here:

https://github.com/threeML/threeML/runs/1773726908?check_suite_focus=true

An additional problem is that if this test fails, this will trigger other tests using the same dataset to fail. For the moment I decided to switch it off.

```
=================================== FAILURES ===================================
_____________________________ test_parallel_pagmo ______________________________

joint_likelihood_bn090217206_nai = <threeML.classicMLE.joint_likelihood.JointLikelihood object at 0x7fcfa3f05e10>

    @skip_if_ROOT_is_available
    def test_parallel_pagmo(joint_likelihood_bn090217206_nai):
    
        with parallel_computation(start_cluster=False):
    
>           test_pagmo(joint_likelihood_bn090217206_nai)

threeML/test/test__minimizers.py:134: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
threeML/test/test__minimizers.py:126: in test_pagmo
    do_analysis(joint_likelihood_bn090217206_nai, pagmo)
threeML/test/test__minimizers.py:56: in do_analysis
    fit_results, like_frame = jl.fit()
threeML/classicMLE/joint_likelihood.py:269: in fit
    compute_covar=False
threeML/minimizer/minimization.py:629: in minimize
    internal_best_fit_values, function_minimum = self._minimize()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <threeML.minimizer.pagmo_minimizer.PAGMOMinimizer object at 0x7fcfa3e053d0>

    def _minimize(self):
    
        # Gather the setup
        islands = self._setup_dict["islands"]
        pop_size = self._setup_dict["population_size"]
        evolution_cycles = self._setup_dict["evolution_cycles"]
    
        # Print some info
        print("\nPAGMO setup:")
        print("------------")
        print("- Number of islands:            %i" % islands)
        print("- Population size per island:   %i" % pop_size)
        print("- Evolutions cycles per island: %i\n" % evolution_cycles)
    
        Npar = len(self._internal_parameters)
    
        if is_parallel_computation_active():
    
            wrapper = PAGMOWrapper(
                function=self.function, parameters=self._internal_parameters, dim=Npar
            )
    
            # use the archipelago, which uses the ipyparallel computation
    
            archi = pg.archipelago(
                udi=pg.ipyparallel_island(),
                n=islands,
                algo=self._setup_dict["algorithm"],
                prob=wrapper,
                pop_size=pop_size,
            )
            archi.wait()
    
            # Display some info
            print("\nSetup before parallel execution:")
            print("--------------------------------\n")
            print(archi)
    
            # Evolve populations on islands
            print("Evolving... (progress not available for parallel execution)")
    
            # For some weird reason, ipyparallel looks for _winreg on Linux (where does
            # not exist, being a Windows module). Let's mock it with an empty module'
            mocked = False
            if os.path.exists("_winreg.py") is False:
    
                with open("_winreg.py", "w+") as f:
    
                    f.write("pass")
    
                mocked = True
    
            archi.evolve()
    
            # Wait for completion (evolve() is async)
    
>           archi.wait_check()
E           RuntimeError: The asynchronous evolution of a pythonic island of type 'Ipyparallel island' raised an error:
E           Traceback (most recent call last):
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/pygmo/_py_islands.py", line 564, in run_evolve
E               ser_algo_pop = pickle.dumps((algo, pop))
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
E               cp.dump(obj)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
E               return Pickler.dump(self, obj)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 437, in dump
E               self.save(obj)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 662, in save_reduce
E               save(state)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 885, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 638, in save_reduce
E               save(args)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 774, in save_tuple
E               save(element)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 638, in save_reduce
E               save(args)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 774, in save_tuple
E               save(element)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 662, in save_reduce
E               save(state)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 890, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 659, in save_reduce
E               self._batch_setitems(dictitems)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 890, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 662, in save_reduce
E               save(state)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 885, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 549, in save
E               self.save_reduce(obj=obj, *rv)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 662, in save_reduce
E               save(state)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 885, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 745, in save_function
E               *self._dynamic_function_reduce(obj), obj=obj
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 687, in _save_reduce_pickle5
E               save(state)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 774, in save_tuple
E               save(element)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 885, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 504, in save
E               f(self, obj) # Call unbound method with explicit self
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 859, in save_dict
E               self._batch_setitems(obj.items())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 890, in _batch_setitems
E               save(v)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/pickle.py", line 524, in save
E               rv = reduce(self.proto)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/numba/core/serialize.py", line 417, in __reduce__
E               return custom_reduce(self._reduce_class(), self._reduce_states())
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/numba/core/dispatcher.py", line 804, in _reduce_states
E               uuid=str(self._uuid),
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/numba/core/dispatcher.py", line 704, in _uuid
E               self._set_uuid(u)
E             File "/usr/share/miniconda/envs/threeML/lib/python3.7/site-packages/numba/core/dispatcher.py", line 708, in _set_uuid
E               assert self.__uuid is None
E           AssertionError
```

**Comment by grburgess** [comment]
I still need to look at this
