### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'logging'

### ISSUE THREAD

**Issue by JohannesBuchner** [threeML/threeML#554]
**Describe the bug**

importing threeML I get the following error

```
WARNING UserWarning: Using default configuration from /home/user/.local/lib/python3.8/site-packages/threeML/data/threeML_config.yml. You might want to copy it to /home/user/.threeML/threeML_config.yml to customize it and avoid this warning.

Traceback (most recent call last):
  File "threemltest.py", line 6, in <module>
    from threeML import *
  File "/home/user/.local/lib/python3.8/site-packages/threeML/__init__.py", line 38, in <module>
    from .io.serialization import *
  File "/home/user/.local/lib/python3.8/site-packages/threeML/io/serialization.py", line 4, in <module>
    from threeML.classicMLE.joint_likelihood import JointLikelihood
  File "/home/user/.local/lib/python3.8/site-packages/threeML/classicMLE/joint_likelihood.py", line 9, in <module>
    import astromodels.core.model
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/__init__.py", line 16, in <module>
    from .core.model import Model
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/model.py", line 16, in <module>
    from astromodels.core.parameter import IndependentVariable, Parameter
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 17, in <module>
    from astromodels.utils.logging import setup_logger
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/utils/logging.py", line 71, in <module>
    get_path_of_log_file("dev.log"), when="D", interval=1, backupCount=10
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/utils/logging.py", line 57, in get_path_of_log_file
    return get_path_of_log_dir() / log_file
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/utils/logging.py", line 34, in get_path_of_log_dir
    user_log: Path = Path(threeML_config.logging.path).expanduser()
AttributeError: 'Config' object has no attribute 'logging'
```

*NOTE:* This is for BUG reports and not questions about generic data analysis.

**To Reproduce**
1. install astromodels and threeML from pip
2. `import * from threeML`

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04

**Comment by JohannesBuchner** [comment]
This is threeml from pip version 2.0.2

**Comment by JohannesBuchner** [comment]
I see now that this is outdated. Installing 2.3.2 ...

**Comment by JohannesBuchner** [comment]
Now I get a different error:

```
20:59:24 WARNING   The naima package is not available. Models that depend on it will not be available                                                                functions.py:50
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it will not be available.                                            functions.py:71
         ERROR     You need to pass either a float or a astropy.Quantity to method _set_value of K                                                                  parameter.py:155
                  ╭────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────╮                 
                  │                                                                                                                                               │                 
                  │ /home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py:127 in handle_quantity                                            │                 
                  │                                                                                                                                               │                 
                  │    124 │   │   │   │                                                                                                                          │                 
                  │    125 │   │   │   │   new_value = input_type(value)                                                                                          │                 
                  │    126 │   │   │   │                                                                                                                          │                 
                  │ ❱  127 │   │   │   │   return method(instance, new_value, *args, **kwargs)                                                                    │                 
                  │    128 │   │   │                                                                                                                              │                 
                  │    129 │   │   │   except TypeError:                                                                                                          │                 
                  │    130                                                                                                                                        │                 
                  │ /home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py:579 in _set_value                                                 │                 
                  │                                                                                                                                               │                 
                  │    576 │   │                                                                                                                                  │                 
                  │    577 │   │   else:                                                                                                                          │                 
                  │    578 │   │   │                                                                                                                              │                 
                  │ ❱  579 │   │   │   new_internal_value = self._transformation.forward(new_value)                                                               │                 
                  │    580 │   │                                                                                                                                  │                 
                  │    581 │   │   # If the parameter has changed, update its value and call the callbacks if                                                     │                 
                  │        needed                                                                                                                                 │                 
                  │    582                                                                                                                                        │                 
                  │                                                                                                                                               │                 
                  │ /home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter_transformation.py:47 in forward                                      │                 
                  │                                                                                                                                               │                 
                  │   44 │   │   with np.errstate(invalid='raise'):                                                                                               │                 
                  │   45 │   │   │                                                                                                                                │                 
                  │   46 │   │   │   # math is 4 times faster than numpy here                                                                                     │                 
                  │ ❱ 47 │   │   │   res = _log10(external_value)                                                                                                 │                 
                  │   48 │   │                                                                                                                                    │                 
                  │   49 │   │   return res                                                                                                                       │                 
                  │   50                                                                                                                                          │                 
                  ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                  UFuncTypeError: ufunc '_log10' did not contain a loop with signature matching types <class 'numpy.dtype[float64]'> -> None                                        
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 127, in handle_quantity
    return method(instance, new_value, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 579, in _set_value
    new_internal_value = self._transformation.forward(new_value)
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter_transformation.py", line 47, in forward
    res = _log10(external_value)
numpy.core._exceptions.UFuncTypeError: ufunc '_log10' did not contain a loop with signature matching types <class 'numpy.dtype[float64]'> -> None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threemltest.py", line 6, in <module>
    from threeML import *
  File "/home/user/.local/lib/python3.8/site-packages/threeML/__init__.py", line 24, in <module>
    from threeML.io.logging import setup_logger
  File "/home/user/.local/lib/python3.8/site-packages/threeML/io/__init__.py", line 1, in <module>
    from .logging import (activate_logs, activate_progress_bars, activate_warnings,
  File "/home/user/.local/lib/python3.8/site-packages/threeML/io/logging.py", line 8, in <module>
    from astromodels import astromodels_config
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/__init__.py", line 16, in <module>
    from .core.model import Model
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/model.py", line 19, in <module>
    from astromodels.functions.function import Function, get_function
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/functions/__init__.py", line 1, in <module>
    from .functions_1D import (Band, Band_Calderone, Band_grbm, Blackbody,
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/functions/functions_1D/__init__.py", line 4, in <module>
    from .functions import (DiracDelta, Exponential_cutoff, Log_parabola, Sin,
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/functions/functions_1D/functions.py", line 548, in <module>
    class Log_parabola(Function1D, metaclass=FunctionMeta):
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/functions/function.py", line 246, in __new__
    this_parameter = FunctionMeta.parse_parameter_definition(
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/functions/function.py", line 637, in parse_parameter_definition
    new_parameter = Parameter(par_name, value, min_value=min_value, max_value=max_value,
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 967, in __init__
    super(Parameter, self).__init__(
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 255, in __init__
    self.value = value
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/node_type.py", line 401, in __setattr__
    return super().__setattr__(name, value)
  File "/home/user/.local/lib/python3.8/site-packages/astromodels/core/parameter.py", line 160, in handle_quantity
    raise TypeError()
TypeError
```

**Comment by JohannesBuchner** [comment]
Same error when uninstalling threeML and reinstalling from dev branch.

**Comment by grburgess** [comment]
@JohannesBuchner this was when you imported things?

**Comment by JohannesBuchner** [comment]
Numba requires numpy < 1.23. I installed numpy 1.22. This however has a bug, see https://github.com/numba/numba/issues/7756

This error message was resolved by replacing numpy 1.22  with 1.22.3

**Comment by JohannesBuchner** [comment]
Now I get

ImportError: cannot import name 'jitclass' from 'numba' (/home/user/.local/lib/python3.8/site-packages/numba/__init__.py)

when doing `from numba import jitclass`

**Comment by JohannesBuchner** [comment]
see https://github.com/numba/numba/issues/6539

**Comment by grburgess** [comment]
This is now fixed on the master and will be released soon. Made version requirements stricter.
