### ISSUE TITLE
using MULTINEST for posterior sampling erro

### ISSUE THREAD

**Issue by Jisans** [threeML/threeML#573]
Hello all, I made an error when using multilinest for posterior sampling 
```
bayes.set_sampler("multinest")
model.test.spectrum.main.shape.mu.prior = Uniform_prior(lower_bound=1, upper_bound=100)
_ = plot_likelihood_function(bayes)
bayes.sampler.setup(n_live_points=400, resume=False)
res = bayes.sample()
```
### error warning:
```
14:09:42 ERROR     multinest is not a valid sampler please choose from                     [bayesian_analysis.py](file:///home/jian/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/bayesian/bayesian_analysis.py):[223](file:///home/jian/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/bayesian/bayesian_analysis.py#223)
                  emcee,dynesty_nested,dynesty_dynamic                                                             
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_15827/3686659251.py in <module>
----> 1 bayes.set_sampler("multinest")
      2 
      3 
      4 model.test.spectrum.main.shape.mu.prior = Uniform_prior(lower_bound=1, upper_bound=100)
      5 

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/bayesian/bayesian_analysis.py in set_sampler(self, sampler_name, **kwargs)
    223                 f"{sampler_name} is not a valid sampler please choose from {','.join(list(_available_samplers.keys()))}")
    224 
--> 225             raise RuntimeError()
    226 
    227         self._sampler = _available_samplers[sampler_name](

RuntimeError:
```
OS:
System: Linux DESKTOP-10UCA6U 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Conda ENV
python v3.12 , threeml v 2.3.2 multilinest v3.10,

**Comment by grburgess** [comment]
It would appear you do not have multinest installed

**Comment by Jisans** [comment]
@grburgess Yep sir. At first, I used `conda list multinest` to show that it was not installed. Later, I used `conda install - c conda-forge multinest. The version is 3.10. After that, the code will still report an error.

**Comment by Jisans** [comment]
Hello all,Does the current 3ML version not integrate the multilinest library?

**Comment by henrikef** [comment]
I think you need to install the pymultinest package as well. Haven't used
it in a while though.

**Comment by grburgess** [comment]
3ml depends on several optional upstream packages. If they are not installed or have errors, then the services that use them will throw an error. You should consult the installation instructions for those packages and try to use them independent of 3ml if you encounter problems.

**Comment by Jisans** [comment]
@grburgess I  know what you said, sir, but I'm a 3ML beginner. I learned my running errors according to the tutorial. I also tried to solve them, but they all failed, so I took the liberty to bother you. I'm sorry!

**Comment by henrikef** [comment]
What is the error you see after having installed multinest and pymultinest
and all their dependencies?

**Comment by kchoX14** [comment]
> @grburgess I  know what you said, sir, but I'm a 3ML beginner. I learned my running errors according to the tutorial. I also tried to solve them, but they all failed, so I took the liberty to bother you. I'm sorry!

I'm a beginner as well, @Jisans . There's a way you could possibly avoid the fuss with Multinest. Johannes (if I recall correct) developed UltraNest as a superior code to overcome issues with the likes of Multinest and Polychord. Only in very high dimensions (> 100 free parameters) does the MLFriends algorithm fail in UltraNest, but one can deselect that to remain safe. Could you possibly use Ultranest instead? I'm unaware if you specifically require Multinest for your work. It returns no error for me. Just a suggestion.

**Comment by grburgess** [comment]
This issue is currently about solving the install of multinest.

**Comment by Jisans** [comment]
@henrikef Sorry for taking so long to return. The warning is as follows:

```
from threeML import *
from threeML.bayesian.tutorial_material import *
```
```
22:12:12 WARNING   The naima package is not available. Models that depend on it will not be         functions.py:51
                  available                                                                                        
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that depend on it  functions.py:72
                  will not be available.                                                                           
22:12:13 WARNING   The ebltable package is not available. Models that depend on it will not be     absorption.py:37
                  available                                                                                        
22:12:13 INFO      Starting 3ML!                                                                     __init__.py:31
         WARNING   ROOT minimizer not available                                                minimization.py:1345
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.


ERROR:   Could not load MultiNest library "libmultinest.so"
ERROR:   You have to build it first,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html


ERROR:   Could not load MultiNest library: libmultinest.so
ERROR:   You have to build MultiNest,
ERROR:   and point the LD_LIBRARY_PATH environment variable to it!
ERROR:   manual: http://johannesbuchner.github.com/PyMultiNest/install.html

problem: libmultinest.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py", line 16, in _load_library
    return cdll.LoadLibrary(libname)
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libmultinest.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_610465/3889831270.py", line 1, in <module>
    from threeML import *
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/__init__.py", line 59, in <module>
    from .io.serialization import *
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/io/serialization.py", line 4, in <module>
    from threeML.classicMLE.joint_likelihood import JointLikelihood
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py", line 26, in <module>
    from threeML.minimizer import minimization
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/minimizer/minimization.py", line 1353, in <module>
    from threeML.minimizer.multinest_minimizer import MultinestMinimizer
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/minimizer/multinest_minimizer.py", line 6, in <module>
    import pymultinest
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/__init__.py", line 19, in <module>
    from .run import run
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py", line 52, in <module>
    lib = _load_library('libmultinest')
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py", line 50, in _load_library
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/home/Jisans/miniconda3/envs/threeML/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py in _load_library(libname)
     15                         libname = find_library(libname)
---> 16                 return cdll.LoadLibrary(libname)
     17         except OSError as e:

~/miniconda3/envs/threeML/lib/python3.7/ctypes/__init__.py in LoadLibrary(self, name)
    441     def LoadLibrary(self, name):
--> 442         return self._dlltype(name)
    443 

~/miniconda3/envs/threeML/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:

OSError: libmultinest.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

/tmp/ipykernel_610465/3889831270.py in <module>
----> 1 from threeML import *
      2 from threeML.bayesian.tutorial_material import *

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/__init__.py in <module>
     58 # Finally import the serialization machinery
---> 59 from .io.serialization import *
     60 # Now import the optimizers first (to avoid conflicting libraries problems)

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/io/serialization.py in <module>
      3 standard_library.install_aliases()
----> 4 from threeML.classicMLE.joint_likelihood import JointLikelihood
      5 from threeML.bayesian.bayesian_analysis import BayesianAnalysis

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/classicMLE/joint_likelihood.py in <module>
     25 from threeML.io.table import Table
---> 26 from threeML.minimizer import minimization
     27 from threeML.parallel.parallel_client import ParallelClient

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/minimizer/minimization.py in <module>
   1352 
-> 1353     from threeML.minimizer.multinest_minimizer import MultinestMinimizer
   1354 

~/miniconda3/envs/threeML/lib/python3.7/site-packages/threeML/minimizer/multinest_minimizer.py in <module>
      5 
----> 6 import pymultinest
      7 from astromodels.functions.priors import Uniform_prior, Log_uniform_prior

~/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/__init__.py in <module>
     18 try:
---> 19         from .run import run
     20         from .solve import solve, Solver

~/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py in <module>
     51 
---> 52 lib = _load_library('libmultinest')
     53 

~/miniconda3/envs/threeML/lib/python3.7/site-packages/pymultinest/run.py in _load_library(libname)
     49                 print('problem:', e)
---> 50                 sys.exit(1)
     51 

SystemExit: 1

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2090                            'the full traceback.\n']
   2091                     stb.extend(self.InteractiveTB.get_exception_only(etype,
-> 2092                                                                      value))
   2093                 else:
   2094                     try:

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    631                     chained_exceptions_tb_offset, context)
    632                 + chained_exception_message
--> 633                 + out_list)
    634 
    635         return out_list

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1366             self.tb = tb
   1367         return FormattedTB.structured_traceback(
-> 1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 
   1370 

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1266             # Verbose modes need a full traceback
   1267             return VerboseTB.structured_traceback(
-> 1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )
   1270         elif mode == 'Minimal':

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1123 
   1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
-> 1125                                                                tb_offset)
   1126 
   1127         colors = self.Colors  # just a shorthand + quicker name lookup

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

~/miniconda3/envs/threeML/lib/python3.7/site-packages/IPython/core/ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()

```

**Comment by grburgess** [comment]
In an ipython session, try and import pymultinest. If this is successful, then it should work in 3ml. You need to make sure the multinest library is in your library path of not.

**Comment by grburgess** [comment]
Ok. It seems you do not have the multinest library installed. You will need to follow the instructions to install it.

**Comment by Jisans** [comment]
But I will try to solve it. Thank you for your help!

**Comment by grburgess** [comment]
We do not support WSL which indeed could be the problem. I would suggest using a Linux flavor.

**Comment by Jisans** [comment]
It's strange that I use 3ML on WSL, astromodels is not bad,

**Comment by henrikef** [comment]
Well, the current issue seems to be with multinest and/or pymultinest, two separate packages. We cannot help with installing external packages.

Additionally, I don't believe any of us are using WSL or have access to a machine to run it, so any support we can provide related to that will be limited.

I'm going to close this issue now. Please only re-open if you still see errors in threeML after you verify that both multinest and pymultinest are working, and you are sure that the error comes from threeML, not one of the external packages.

Good luck!
