### ISSUE TITLE
After installation, Issue with: "From threeml import * "

### ISSUE THREAD

**Issue by aplangrangian** [threeML/threeML#603]
**Describe the bug**
I'm having trouble installing 3ML. I've used the instructions on the installation page. Everything seems to install correctly, however, when I try to import 3ML packages using "from threeML import *" I run into the following error:

PermissionError: [Errno 13] Permission denied: '/User/.config/astromodels'

To replicate:
I create a fresh conda environment:
"conda create --name threeML -c conda-forge python=3.9 numpy scipy matplotlib"
activate the environment:
"conda activate threeML"
and install threeml and astromodels
"conda install -c conda-forge -c threeml astromodels threeml"

Upon installation, I open up python in my console in the same newly created environment and test the "from threeML import *" import and produces:

>>> from threeML import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/__init__.py", line 24, in <module>
    from threeML.io.logging import setup_logger
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/io/__init__.py", line 1, in <module>
    from .logging import (activate_logs, activate_progress_bars, activate_warnings,
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/io/logging.py", line 7, in <module>
    from astromodels import astromodels_config
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/__init__.py", line 14, in <module>
    from .utils.configuration import astromodels_config
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/utils/configuration.py", line 12, in <module>
    for user_config_file in get_path_of_user_config().glob("*.yml"):
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/utils/file_utils.py", line 69, in get_path_of_user_config
    config_path.mkdir(parents=True)
  File "/opt/anaconda3/envs/threeML/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Users/alexlange/.config/astromodels'

I am running on Mac OS Big Sur 11.6

Is this just a pathing issue/can this be remedied with a sudo install?

**Comment by aplangrangian** [comment]
it seems all I needed to do was create an empty directory at /User/.config/ for astromodels and threeML respectively. After doing that, all threeML and Astromodel tools seem to work and I can proceed with the tutorials.
