### ISSUE TITLE
Error in following 3ML tutorial " Analyzing GRB 080916C"

### ISSUE THREAD

**Issue by poff22** [threeML/threeML#610]
Hello, I'm following 3ML tutorial " Analyzing GRB 080916C" for my respective GRBS : GRB100826957 and GRB 130828306. I keep coming across an error on step number 8. I have attached below a screenshot of the error which happens to appear for both of the GRBs mentioned above.
Kindly assist me in how I should proceed with this.

![6](https://user-images.githubusercontent.com/113614386/220315461-8b2a1b6e-e515-4d26-a898-aac26325cdb6.png)

**Comment by grburgess** [comment]
It looks like you are trying to select an interval not covered in the GBM RSP2 matrix

**Comment by poff22** [comment]
Yes i understand that the interval is not being covered by the matrix but I haven't set or defined any interval for the GRB on my own. According to the code the GRB data is automatically donwloaded from GBM burst catalog and so the intervals are predefined.
So i dont understand why this error appears .Do you have any suggestions as to what could be causing it and how I should proceed?

**Comment by grburgess** [comment]
The interval must have been defined. If you can provide a formatted code example that would be more useful.

**Comment by poff22** [comment]
[GRB_100826957_GBM_analysis.txt](https://github.com/threeML/threeML/files/10811368/GRB_100826957_GBM_analysis.txt)

**Comment by poff22** [comment]
I have shared the code I am following above. Looking forward to your response.

**Comment by grburgess** [comment]
Please include the code with formatting within the issue.

**Comment by poff22** [comment]
[terminal.txt](https://github.com/threeML/threeML/files/10836058/terminal.txt)
[response.txt](https://github.com/threeML/threeML/files/10836061/response.txt)


I have attached above two files. FIle that goes by the name of terminal consists of the output we get when we run the code on the temrinal.
respont file is the code found in threeML packages - the error appears to be found in line 1115. 

I hope these are the files you are referring to - if not then please guide me as to which file i sould share.

**Comment by grburgess** [comment]
Please follow the issue templates. Code should be included as formatted markdown. Not as "txt" files

**Comment by henrikef** [comment]
@poff22 

It is much safer and easier to read if you include your code and log file in the issue text in between three ` signs. It will show up like so, properly formatted:

```python
#python code goes here
import threeML
```

You do not need to upload threeML code here, only code or scripts you yourself wrote and the output you get, so that we can duplicate the issue.

Now in your case, I saw that there's a bug in printing the error message. Fixing that, I get the following error:

```
The interval of interest (time interval 8.704 - 93.697 (duration: 84.993)) end is not covered by time interval 46.59272199869156 - 82.94527196884155 (duration: 36.352549970149994)
```

So, the interval of interest is from 8.7 to 93.7 seconds, but the response is only valid until 82.9 s.

I cannot help further but for @grburgess , here's the code to reproduce the error:

```python
import warnings
warnings.simplefilter("ignore")
import matplotlib.pyplot as plt
import numpy as np
np.seterr(all="ignore")
from threeML import *
from threeML.io.package_data import get_path_of_data_file
gbm_catalog = FermiGBMBurstCatalog()
gbm_catalog = FermiGBMBurstCatalog()
gbm_catalog.query_sources("GRB100826957")
grb_info = gbm_catalog.get_detector_information()["GRB100826957"]
gbm_detectors = grb_info["detectors"]
source_interval = grb_info["source"]["fluence"]
background_interval = grb_info["background"]["full"]
best_fit_model = grb_info["best fit model"]["fluence"]
model = gbm_catalog.get_model(best_fit_model, "fluence")["GRB100826957"]
model
dload = download_GBM_trigger_data("bn100826957", detectors=gbm_detectors)
fluence_plugins = []
time_series = {}
for det in gbm_detectors:
    ts_cspec = TimeSeriesBuilder.from_gbm_cspec_or_ctime(det, cspec_or_ctime_file=dload[det]["cspec"],rsp_file=dload[det]["rsp"])
    ts_cspec.set_background_interval(*background_interval.split(","))
    ts_cspec.save_background(f"{det}_bkg.h5", overwrite=True)
    ts_tte = TimeSeriesBuilder.from_gbm_tte(det,tte_file=dload[det]["tte"],rsp_file=dload[det]["rsp"],restore_background=f"{det}_bkg.h5",)
    time_series[det] = ts_tte
    ts_tte.set_active_time_interval(source_interval)
    ts_tte.view_lightcurve(-40, 100)
    fluence_plugin = ts_tte.to_spectrumlike()
    if det.startswith("b"):
        fluence_plugin.set_active_measurements("250-30000")
    else:
        fluence_plugin.set_active_measurements("9-900")
    fluence_plugin.rebin_on_background(1.0)
    fluence_plugins.append(fluence_plugin)
```

And here's the output

```
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
08:59:40 WARNING   The naima package is not available. Models that depend on it will not  functions.py:50
                  be available                                                                           
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that     functions.py:71
                  depend on it will not be available.                                                    
         WARNING   The ebltable package is not available. Models that depend on it will  absorption.py:36
                  not be available                                                                       
08:59:41 INFO      Starting 3ML!                                                           __init__.py:35
         WARNING   WARNINGs here are NOT errors                                            __init__.py:36
         WARNING   but are inform you about optional packages that can be installed        __init__.py:37
         WARNING    to disable these messages, turn off start_warning in your config file  __init__.py:40
         WARNING   ROOT minimizer not available                                      minimization.py:1345
         WARNING   PyGMO is not available                                            minimization.py:1369
08:59:41 WARNING   The cthreeML package is not installed. You will not be able to use      __init__.py:94
                  plugins which require the C/C++ interface (currently HAWC)                             
08:59:42 WARNING   Could not import plugin HAWCLike.py. Do you have the relative          __init__.py:144
                  instrument software installed and configured?                                          
         WARNING   Env. variable OMP_NUM_THREADS is not set. Please set it to 1 for       __init__.py:387
                  optimal performances in 3ML                                                            
         WARNING   Env. variable MKL_NUM_THREADS is not set. Please set it to 1 for       __init__.py:387
                  optimal performances in 3ML                                                            
         WARNING   Env. variable NUMEXPR_NUM_THREADS is not set. Please set it to 1 for   __init__.py:387
                  optimal performances in 3ML                                                            
09:00:10 INFO      Building cache for fermigbrst                       get_heasarc_table_as_pandas.py:112
<Table length=1>
    name        ra     dec    trigger_time   t90  
   object    float64 float64    float64    float64
------------ ------- ------- ------------- -------
GRB100826957 284.000 -23.190 55434.9572095  84.993

Model summary:
==============

                  N
Point sources     1
Extended sources  0
Particle sources  0

Free parameters (4):
--------------------
                                          value min_value max_value  \
GRB100826957.spectrum.main.Band.K      0.035517      None      None   
GRB100826957.spectrum.main.Band.alpha -0.810843      -1.5       3.0   
GRB100826957.spectrum.main.Band.xp     263.2545      10.0      None   
GRB100826957.spectrum.main.Band.beta  -1.918037      -5.0      -1.6   

                                                 unit  
GRB100826957.spectrum.main.Band.K      keV-1 s-1 cm-2  
GRB100826957.spectrum.main.Band.alpha                  
GRB100826957.spectrum.main.Band.xp                keV  
GRB100826957.spectrum.main.Band.beta                   

Fixed parameters (3):
(abridged. Use complete=True to see all fixed parameters)


Properties (0):
--------------------

(none)


Linked parameters (0):
----------------------

(none)

Independent variables:
----------------------

(none)

Linked functions (0):
----------------------

(none)

Downloading glg_cspec_n7_bn100826957_v00.pha: 100%|███████████████████| 506k/506k [00:06<00:00, 79.3kB/s]
Downloading glg_cspec_n7_bn100826957_v01.rsp2: 100%|██████████████████| 340k/340k [00:05<00:00, 63.8kB/s]
Downloading glg_tte_n7_bn100826957_v00.fit: 100%|████████████████████| 4.88M/4.88M [00:22<00:00, 225kB/s]
Downloading glg_cspec_n8_bn100826957_v00.pha: 100%|████████████████████| 506k/506k [00:02<00:00, 213kB/s]
Downloading glg_cspec_n8_bn100826957_v01.rsp2: 100%|███████████████████| 340k/340k [00:02<00:00, 146kB/s]
Downloading glg_tte_n8_bn100826957_v00.fit: 100%|████████████████████| 4.56M/4.56M [00:43<00:00, 111kB/s]
Downloading glg_cspec_b1_bn100826957_v00.pha: 100%|███████████████████| 506k/506k [00:06<00:00, 83.0kB/s]
Downloading glg_cspec_b1_bn100826957_v01.rsp2: 100%|██████████████████| 340k/340k [00:03<00:00, 94.4kB/s]
Downloading glg_tte_b1_bn100826957_v00.fit: 100%|████████████████████| 8.17M/8.17M [00:37<00:00, 227kB/s]
09:12:48 WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 1) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
Loading PHAII Spectra: 100%|███████████████████████████████████████| 1742/1742 [00:00<00:00, 1986.22it/s]
09:12:49 WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 1) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 2) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 3) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 4) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
Finding best polynomial Order: 100%|███████████████████████████████████████| 5/5 [00:02<00:00,  2.30it/s]
09:12:52 INFO      Auto-determined polynomial order: 1                      binned_spectrum_series.py:389
Fitting GBM_NAI_07 background: 100%|███████████████████████████████████| 128/128 [00:08<00:00, 15.96it/s]
09:13:00 INFO      None 1-order polynomial fit with the mle method                     time_series.py:458
         INFO      Saved fitted background to n7_bkg.h5                               time_series.py:1064
         INFO      Saved background to n7_bkg.h5                               time_series_builder.py:471
         WARNING   The TTE file                                                            gbm_data.py:43
                  /mnt/10A6B451A6B438D4/FYP/glg_tte_n7_bn100826957_v00.fit.gz contains                   
                  duplicate time tags and is thus invalid. Contact the FSSC                              
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 1) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 2) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 3) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   The default choice for MATRIX extension failed:KeyError("Extension     response.py:466
                  ('MATRIX', 4) not found.")available: None 'EBOUNDS' 'SPECRESP MATRIX'                  
                  'SPECRESP MATRIX' 'SPECRESP MATRIX' 'SPECRESP MATRIX'                                  
         WARNING   No TLMIN keyword found. This DRM does not follow OGIP standards.       response.py:601
                  Assuming TLMIN=1                                                                       
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         WARNING   Minimum MC energy (5.0) is larger than minimum EBOUNDS energy          response.py:137
                  (4.511000156402588)                                                                    
         INFO      Successfully restored fit from n7_bkg.h5                    time_series_builder.py:171
         ERROR     The interval of interest (time interval 8.704 - 93.697 (duration:     response.py:1115
                  84.993)) is not covered by time interval 8.704 - 9.72817200422287                      
                  (duration: 1.0241720042228692)                                                         
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/home/ayesha/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/utils/data_builders/time_series_builder.py", line 257, in set_active_time_interval
    self._response = self._weighted_rsp.weight_by_counts(
  File "/home/ayesha/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/utils/OGIP/response.py", line 970, in weight_by_counts
    return self._get_weighted_matrix("counts", *intervals)
  File "/home/ayesha/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/utils/OGIP/response.py", line 987, in _get_weighted_matrix
    weights += self._weight_response(interval, switch)
  File "/home/ayesha/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/utils/OGIP/response.py", line 1118, in _weight_response
    raise IntervalOfInterestNotCovered( )
threeML.utils.OGIP.response.IntervalOfInterestNotCovered

```

I'll push a fix for the error message.

**Comment by grburgess** [comment]
Thanks @henrikef. @poff22 Indeed you chose time intervals which are not covered by the RSP2 files. This is an issue with the fermi GBM catalog and outside of the control of the 3ml team. It is best to contact the FSSC.

**Comment by poff22** [comment]
Thank you for your response.
Previously I carried out an analysis of a GRB (not using 3ML) and in it i utilized a python code to generate response files .I was wondering if I could use the same process to generate RSP2 files of this particuar GRB and then use it in 3ML : Is there a way for me to utlize these generated RSP2 files in 3ML?

**Comment by grburgess** [comment]
If they are compliant OGIP files then they can be used.

**Comment by poff22** [comment]
In case they are OGIP files, how should i proceed with this? Any tips or suggestions as to how i may use these files in 3ML?

**Comment by astroboysanju** [comment]
Hi, i'm following 3ml tutorials, my interest is "Example joint fit between GBM and Swift BAT"   in the very beginning of the analysis few commands are the to read the data from BAT 
-> bat_pha = get_path_of_data_file("datasets/bat/gbm_bat_joint_BAT.pha")
->bat_rsp = get_path_of_data_file("datasets/bat/gbm_bat_joint_BAT.rsp")
if any one wants  to analyze their interested GRB (any other GRB) how to upload that ? how to get those  .pha and .rsp files and how to upload that in the database?

**Comment by yash739** [comment]
Facing the same issue, any response would be appreciated
