### ISSUE TITLE
Error related to initialisation the threeML package 

### ISSUE THREAD

**Issue by ajaykhoj** [threeML/threeML#632]
Dear Sir,

I am using a MacBook Air with version 14.5. I have installed the package with conda as documented. But when I tried to initialize the package, I got a permission denied error, which is given below. This may be due to an incorrect way of installing the package or something else. Please help me to solve this problem.

>>> from threeML import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/__init__.py", line 24, in <module>
    from threeML.io.logging import setup_logger
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/io/__init__.py", line 1, in <module>
    from .logging import (activate_logs, activate_progress_bars, activate_warnings,
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/threeML/io/logging.py", line 7, in <module>
    from astromodels import astromodels_config
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/__init__.py", line 14, in <module>
    from .utils.configuration import astromodels_config, show_configuration
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/utils/configuration.py", line 17, in <module>
    for user_config_file in get_path_of_user_config().glob("*.yml"):
  File "/opt/anaconda3/envs/threeML/lib/python3.9/site-packages/astromodels/utils/file_utils.py", line 72, in get_path_of_user_config
    config_path.mkdir(parents=True)
  File "/opt/anaconda3/envs/threeML/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Users/ajaysharma/.config/astromodels'

**Comment by omodei** [comment]
Do you have permission to write in /Users/ajaysharma/.config ? Make sure to give write permissions
