### ISSUE TITLE
getting error while importing threeml package

### ISSUE THREAD

**Issue by ajaykhoj** [threeML/threeML#633]
Hi, 
I installed this package in Mac Air (M1) using the following commands:
First, i created virt envir. using " conda create --name threeml -c conda-forge -c xspecmodels python=3.9 xspec-modelsonly numpy scipy matplotlib" .  Later, I used the "conda install -c conda-forge -c threeml astromodels threeml" command to install the threeml, astromodels packages. 

After that, when I tried to import this package, got errors, given as:
>>> from threeML import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/threeML/__init__.py", line 24, in <module>
    from threeML.io.logging import setup_logger
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/threeML/io/__init__.py", line 1, in <module>
    from .logging import (activate_logs, activate_progress_bars, activate_warnings,
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/threeML/io/logging.py", line 7, in <module>
    from astromodels import astromodels_config
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/astromodels/__init__.py", line 14, in <module>
    from .utils.configuration import astromodels_config, show_configuration
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/astromodels/utils/configuration.py", line 4, in <module>
    from omegaconf import OmegaConf
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/__init__.py", line 1, in <module>
    from .base import Container, DictKeyType, Node, SCMode
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/base.py", line 11, in <module>
    from ._utils import (
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/_utils.py", line 32, in <module>
    from .grammar_parser import SIMPLE_INTERPOLATION_PATTERN, parse
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/grammar_parser.py", line 12, in <module>
    from .grammar_visitor import (  # type: ignore
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/grammar_visitor.py", line 25, in <module>
    from omegaconf.grammar.gen.OmegaConfGrammarLexer import OmegaConfGrammarLexer
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarLexer.py", line 254, in <module>
    class OmegaConfGrammarLexer(Lexer):
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/omegaconf/grammar/gen/OmegaConfGrammarLexer.py", line 256, in OmegaConfGrammarLexer
    atn = ATNDeserializer().deserialize(serializedATN())
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/antlr4/atn/ATNDeserializer.py", line 28, in deserialize
    self.checkVersion()
  File "/opt/anaconda3/envs/threeml/lib/python3.9/site-packages/antlr4/atn/ATNDeserializer.py", line 50, in checkVersion
    raise Exception("Could not deserialize ATN with version {} (expected {}).".format(ord(version), SERIALIZED_VERSION))
Exception: Could not deserialize ATN with version 3 (expected 4).

How to resolve these errors.

**Comment by omodei** [comment]
Hi! the version for M1 mac processor of threeML is on the dev version. Try this for your second installation command:
`conda install -c conda-forge -c threeml/label/dev astromodels threeml`
