### ISSUE TITLE
ROOT version 6.32+ prevents threeML from working for python3.12+

### ISSUE THREAD

**Issue by torresramiro350** [threeML/threeML#634]
**PLEASE FOLLOW THE TEMPLATE**

**Describe the bug**
A clear and concise description of what the bug is. What data are you using and how was it obtained? Which plugin(s) are you using?

After generating a fresh conda environment with threeML on a CentOS7 system for python3.12+, I get the following error when importing threeML. To replicate this, simply `python -c "import threeML"`. The dependencies for a conda environment prevent the usage of any earlier versions of ROOT. 

Include output with either:

```bash
$ python -c "import threeML"
15:03:41 WARNING   The naima package is not available. Models that depend on it will not  functions.py:48
                  be available
         WARNING   The GSL library or the pygsl wrapper cannot be loaded. Models that     functions.py:69
                  depend on it will not be available.
15:03:42 WARNING   The ebltable package is not available. Models that depend on it will  absorption.py:33
                  not be available
cling::DynamicLibraryManager::loadLibrary(): libgsl.so.25: cannot open shared object file: No such file or directory
Error in <TInterpreter::TCling::AutoLoad>: failure loading library libMathMore.so for ROOT::Math::EGSLMinimizerType
input_line_35:38:23: error: expected '(' for function-style cast or type construction
      return unsigned int{};
             ~~~~~~~~ ^
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/disk01/home/torresramiro350/hawc_software/miniconda3/envs/hal_312/lib/python3.12/site-packages/threeML/__init__.py", line 70, in <module>
    from .io.serialization import *
  File "/data/disk01/home/torresramiro350/hawc_software/miniconda3/envs/hal_312/lib/python3.12/site-packages/threeML/io/serialization.py", line 4, in <module>
    from threeML.classicMLE.joint_likelihood import JointLikelihood
  File "/data/disk01/home/torresramiro350/hawc_software/miniconda3/envs/hal_312/lib/python3.12/site-packages/threeML/classicMLE/joint_likelihood.py", line 27, in <module>
    from threeML.minimizer import minimization
  File "/data/disk01/home/torresramiro350/hawc_software/miniconda3/envs/hal_312/lib/python3.12/site-packages/threeML/minimizer/minimization.py", line 1341, in <module>
    from threeML.minimizer.ROOT_minimizer import ROOTMinimizer
  File "/data/disk01/home/torresramiro350/hawc_software/miniconda3/envs/hal_312/lib/python3.12/site-packages/threeML/minimizer/ROOT_minimizer.py", line 45, in <module>
    class FuncWrapper(ROOT.Math.IMultiGenFunction):
TypeError: no python-side overrides supported (failed to compile the dispatcher code)
```

*NOTE:* This is for BUG reports and not questions about generic data analysis.

**To Reproduce**

Include python code like this

```python
# your code here!
import threeML
```

**Expected behavior**

The module should be successfully loaded for usage.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

This might be an issue with ROOT itself, but I wanted to let the developers know about this.

**Comment by torresramiro350** [comment]
@omodei
